#!/bin/bash
# Copyright (c) 2016 Deepin Ltd. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# Disable disk-mount plugin.
deepin-installer-settings set \
  "~/.config/dde-file-manager/dde-file-manager.conf" \
  "advance.mount.auto_mount" value false

deepin-installer-settings set \
  "~/.config/deepin/dde-file-manager/dde-file-manager.conf" \
  "advance.mount.auto_mount" value false

# Kill docker process.
pkill -f dde-dock

pkexec "/usr/bin/deepin-installer-reborn" "$@"