#!/bin/bash
#
# Copyright (C) 2017 ~ 2018 Deepin Technology Co., Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Disable disk-mount plugin.
deepin-installer-settings set \
  "$HOME/.config/dde-file-manager/dde-file-manager.conf" \
  "advance.mount.auto_mount" value false

deepin-installer-settings set \
  "$HOME/.config/deepin/dde-file-manager/dde-file-manager.conf" \
  "advance.mount.auto_mount" value false

# Kill docker process.
pkill -f dde-dock

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
if [ x$(whoami) == 'xroot' ]; then
  /usr/bin/deepin-installer $@
else
  pkexec "/usr/bin/deepin-installer" "$@"
fi
