#!/bin/bash
# Copyright (c) 2016 Deepin Ltd. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# Generate background image of installer with blur effect.
# Enable all locales defined in language list.

# NOTE(xushaohua): This script is used to speed up installer program.
# Also it is ok to generate blur-image when installer program is startup,
# it takes some seconds to minutes to do this job.
# Call service/system_language.h::GenerateLocale() in SystemLanguageFrame
# may also update system locale based on using settings, it is not so fluent
# before switching to SystemInfoFrame.


# Absolute path to installer misc folder.
SHARE_DIR=/usr/share/deepin-installer-reborn

# Update /etc/locale.gen and generate new locale cache.
generate_locale() {
  local JSON="${SHARE_DIR}/resources/languages.json"
  local LOCALES
  LOCALES=$(grep 'locale' "${JSON}" | awk '{ print $2 }' | \
            sed 's/"//g'  | sed 's/,//g')

  echo "locales: ${LOCALES}"
  for LOCALE_NAME in $(echo "${LOCALES}"); do
    echo "${LOCALE_NAME}"
    sed -i "s/# \(${LOCALE_NAME}\.UTF-8.*$\)/\1/g" /etc/locale.gen
  done

  locale-gen
}

# Generate new background image.
generate_background_image() {
  local SRC="/usr/share/backgrounds/default_background.jpg"
  local DST="${SHARE_DIR}/resources/default_wallpaper.jpg"
  if [ -f "${SRC}" ]; then
    echo "Generate default wallpaper.."
    convert "${SRC}" -resize 25% -brightness-contrast -10 \
      -modulate 100,120,100 -blur 0x16 -resize 400% "${DST}"
  fi
}

# Remove slide image for netease-cloud-music on non-x86 platforms
remove_cloud_music_slide() {
  case $(uname -m) in
    i386 | amd64 | x86 | x86_64)
      # Do nothing.
      return 0
      ;;
    *)
      ;;
  esac

  local ZH_CN_SLIDE="${SHARE_DIR}/resources/slide/zh_CN/18.png"
  local ZH_TW_SLIDE="${SHARE_DIR}/resources/slide/zh_TW/18.png"
  [ -f "${ZH_CN_SLIDE}" ] && rm "${ZH_CN_SLIDE}"
  [ -f "${ZH_TW_SLIDE}" ] && rm "${ZH_TW_SLIDE}"

  return 0
}

# Replace default settings on loongson/sw platform.
replace_default_settings() {
  case $(uname -m) in
    mips*)
      if [ -f "${SHARE_DIR}/resources/loongson_default_settings.ini" ]; then
        /bin/cp -f "${SHARE_DIR}/resources/loongson_default_settings.ini" \
          "${SHARE_DIR}/resources/default_settings.ini"
      fi
      ;;
    sw*)
      if [ -f "${SHARE_DIR}/resources/sw_default_settings.ini" ]; then
        /bin/cp -f "${SHARE_DIR}/resources/sw_default_settings.ini" \
          "${SHARE_DIR}/resources/default_settings.ini"
      fi
      ;;
    *)
      # Do nothing
      ;;
  esac
}

generate_locale
generate_background_image
remove_cloud_music_slide
replace_default_settings
