#!/bin/sh
# Copyright (c) 2016 Deepin Ltd. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# If in live mode, replace default lightdm.conf, launch installer instead of
# default lightdm greeter.

generate_lightdm_conf() {
  local CONF_FILE="$1"
  cat > "${CONF_FILE}" <<EOF
[Seat:*]
greeter-setup-script=/usr/bin/deepin-installer-reborn-pkexec
EOF
}

# Parse live config cmdline to check whether in live mode.
parse_cmdline () {
  # Reading kernel command line
  for _PARAMETER in ${LIVE_CONFIG_CMDLINE}; do
    case "${_PARAMETER}" in
      live-config.livecd-installer|livecd-installer)
        LIVE_MODE=true
        ;;
    esac
  done
}

# Setup lightdm if in live mode.
config_live_mode() {
  if [ x"$LIVE_MODE" = "xtrue" ]; then
    generate_lightdm_conf /etc/lightdm/lightdm.conf
  fi
}

parse_cmdline
config_live_mode