#!/bin/sh
# Copyright (c) 2016 Deepin Ltd. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# try to fix systemd machine-id config at first boot

oldMachineID="/deepinhost/var/cache/machine-id"
if [ -f "${oldMachineID}" ]; then
  install -m644 $oldMachineID /etc/
else
  systemd-machine-id-setup
fi

chmod 644 /etc/machine-id

return 0
