#! /bin/sh
# Copyright (c) 2016 Deepin Ltd. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# Disable 'auto dhcp' interfaces if network-manager is in use.
# when use PXE install system will cause this problem.

if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
  sed  -i 's/managed=false/managed=true/' /etc/NetworkManager/NetworkManager.conf
fi
