#! /bin/bash
# Copyright (c) 2016 Deepin Ltd. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# Fix program file capacity flags caused by squashfs filesystem.

for pkg in libgstreamer1.0-0 systemd iputils-ping netselect; do
  dpkg -l | grep -q -e  "^ii\ \ ${pkg}\ " && \
    dpkg-reconfigure --frontend noninteractive ${pkg} || true
done

exit 0
