#! /bin/bash
# Copyright (c) 2016 Deepin Ltd. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# Refresh gtk2 and gtk3 im-modules cache

msg "Refresh gtk2 and gtk3 im-modules cache"
if dpkg -l | grep -q ^ii\ \ libgtk2.0-0;then
  dpkg-reconfigure libgtk2.0-0 || true
fi

if dpkg -l | grep -q ^ii\ \ libgtk-3-0;then
  dpkg-reconfigure libgtk-3-0 || true
fi

return 0
