#!/bin/sh
# Copyright (c) 2016 Deepin Ltd. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

# Copy desktop wallpaper to system folder

OEM_WALLPAPER="$OEM_DIR/background.jpg"
SYS_WALLPAPER=/usr/share/backgrounds/desktop.jpg

if [ -f "${OEM_WALLPAPER}" ]; then
  install -m644 -v "${OEM_WALLPAPER}" "${SYS_WALLPAPER}" || \
    warn_exit "Failed to copy wallpaper to system"
  chmod a+r "${SYS_WALLPAPER}"
fi

return 0
